### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by ccleve** [lalrpop/lalrpop#651]
#650 has made it not possible (for me, at least) to do even a hello world. To try to dig into the problem a little more, I tried to get the lalrpop-tests crate to work. It fails with a bunch of warnings and then an error. To duplicate, run this script:

```
git clone https://github.com/lalrpop/lalrpop.git
cd lalrpop
git checkout tags/0.19.7
cd lalrpop-test
cargo test

```

There's too much output to paste here, but basically it shows a bunch of warnings like this:

```
warning: trailing semicolon in macro used in expression position
   --> lalrpop/src/normalize/mod.rs:22:11
    |
22  |           });
    |             ^
    |
   ::: lalrpop/src/normalize/prevalidate/mod.rs:158:42

```

Then it compiles ok and runs the tests. Most pass, but then it fails here:

```
failures:

---- verify_lalrpop_generates_itself stdout ----
thread 'verify_lalrpop_generates_itself' panicked at 'lalrpop run failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }', lalrpop-test/src/lib.rs:1045:10
stack backtrace:
   0: rust_begin_unwind
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::expect
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/result.rs:1255:23
   4: lalrpop_test::verify_lalrpop_generates_itself
             at ./src/lib.rs:1034:13
   5: lalrpop_test::verify_lalrpop_generates_itself::{{closure}}
             at ./src/lib.rs:1025:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

This might be the same problem as #650

**Comment by Pat-Lafon** [comment]
The warning mentioned here has since been fixed. The error here I believe is separate in that you need to run `update_lrgrammar.sh` to run that particular test. See https://github.com/lalrpop/lalrpop/blob/master/CONTRIBUTING.md

I'll close this as completed, please reopen this if there is something I missed.
